version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student_and_teacher
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Qasaqayj7
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: student_and_teacher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qasaqayj7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
